
import pandas as pd
import numpy as np
import argparse
import os
import sys

def verify_student_teacher_alignment(student_df_path, teacher_uid_path):
    """
    Verify that the UIDs in the student's dataframe match strictly with the UIDs in the teacher's output file.
    
    Args:
        student_df_path (str): Path to train_data.df (DLLM2Rec input)
        teacher_uid_path (str): Path to *_uid.txt (BIGRec output)
    """
    print("="*80)
    print("Data Alignment Verification: Student (DataFrame) vs Teacher (TXT)")
    print("="*80)
    print(f"Student Data: {student_df_path}")
    print(f"Teacher UID : {teacher_uid_path}")
    
    # 1. Load Student Data
    if not os.path.exists(student_df_path):
        print(f"Error: Student data file not found: {student_df_path}")
        return False
        
    print("Loading student data...")
    df = pd.read_pickle(student_df_path)
    if 'uid' not in df.columns:
        print("Error: 'uid' column missing in student train_data.df.")
        return False
    
    student_uids = df['uid'].tolist()
    print(f"Loaded {len(student_uids)} records from student data.")
    
    # 2. Load Teacher Data
    if not os.path.exists(teacher_uid_path):
        print(f"Error: Teacher UID file not found: {teacher_uid_path}")
        return False
        
    print("Loading teacher UID data...")
    with open(teacher_uid_path, 'r') as f:
        # Read lines and filter out empty lines
        teacher_uids = [line.strip() for line in f if line.strip()]
        
    # Convert to int (handling potential errors)
    try:
        teacher_uids = [int(uid) for uid in teacher_uids]
    except ValueError as e:
        print(f"Error: Failed to parse teacher UIDs as integers. {e}")
        return False
        
    print(f"Loaded {len(teacher_uids)} records from teacher data.")
    
    # 3. Verify Length
    if len(student_uids) != len(teacher_uids):
        print(f"FAILURE: Record count mismatch! Student: {len(student_uids)}, Teacher: {len(teacher_uids)}")
        return False
        
    # 4. Verify Content
    mismatches = 0
    for i, (s_uid, t_uid) in enumerate(zip(student_uids, teacher_uids)):
        if s_uid != t_uid:
            print(f"Mismatch at index {i}: Student UID {s_uid} != Teacher UID {t_uid}")
            mismatches += 1
            if mismatches >= 10:
                print("Too many mismatches. stopping.")
                break
    
    if mismatches == 0:
        print("SUCCESS: Student and Teacher data are perfectly aligned!")
        return True
    else:
        print(f"FAILURE: Found {mismatches} mismatches.")
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Verify alignment between DLLM2Rec train data and BIGRec output UIDs.")
    parser.add_argument("--student_data", type=str, required=True, help="Path to train_data.df")
    parser.add_argument("--teacher_uid", type=str, required=True, help="Path to *_uid.txt generated by evaluate.py")
    
    args = parser.parse_args()
    
    success = verify_student_teacher_alignment(args.student_data, args.teacher_uid)
    
    if not success:
        sys.exit(1)
        
