#!/bin/bash

# Exit on error
set -e

# Arguments
DATASET=${1:-movie}

echo "Transferring data for dataset: $DATASET"

# Define paths
BIGREC_DIR="BIGRec"
DLLM2REC_DIR="DLLM2Rec"
TOCF_DIR="$DLLM2REC_DIR/tocf/$DATASET"

# Ensure destination directory exists
mkdir -p "$TOCF_DIR"

# Copy files
# Note: The README says to copy "all_embeddings.pt", "myrank_train.txt", "confidence_train.txt"
# We need to ensure these files are actually generated by BIGRec's evaluate.py or similar.
# The BIGRec README mentions `evaluate.py` and `adjust_ci.py`.
# DLLM2Rec README says:
# "all_embeddings.pt" (num_item X llm_emb_size) : refer to "predict_embeddings" in BIGRec/data/movie/evaluate.py
# "myrank_train.txt" : refer to "rank" in BIGRec/data/movie/evaluate.py
# "confidence_train.txt" : refer to "dist" in BIGRec/data/movie/evaluate.py

# Since BIGRec's evaluate.py doesn't seem to save these by default (it just prints or saves json),
# we might need to modify evaluate.py or assume the user runs a modified version.
# For now, I will assume the files are generated in BIGRec/data/$DATASET/ or similar after running evaluate.py
# OR I should create a script to generate them.

# Let's assume we run a generation script here.
# For now, I'll just try to copy them if they exist, or warn.

SRC_DIR="$BIGREC_DIR/data/$DATASET"

if [ -f "$SRC_DIR/all_embeddings.pt" ]; then
    cp "$SRC_DIR/all_embeddings.pt" "$TOCF_DIR/"
    echo "Copied all_embeddings.pt"
else
    echo "Warning: all_embeddings.pt not found in $SRC_DIR"
fi

if [ -f "$SRC_DIR/myrank_train.txt" ]; then
    cp "$SRC_DIR/myrank_train.txt" "$TOCF_DIR/"
    echo "Copied myrank_train.txt"
else
    echo "Warning: myrank_train.txt not found in $SRC_DIR"
fi

if [ -f "$SRC_DIR/confidence_train.txt" ]; then
    cp "$SRC_DIR/confidence_train.txt" "$TOCF_DIR/"
    echo "Copied confidence_train.txt"
else
    echo "Warning: confidence_train.txt not found in $SRC_DIR"
fi

echo "Data transfer completed."
