#!/bin/bash

# Exit on error
set -e

# Arguments
DATASET=${1:-movie}
GPU_ID=${2:-0}
BASE_MODEL=${3:-"Qwen/Qwen2-0.5B"}
SEED=${4:-0}
SAMPLE=${5:-1024}

echo "Transferring data for dataset: $DATASET"
echo "GPU ID: $GPU_ID"
echo "Base Model: $BASE_MODEL"
echo "Seed: $SEED"
echo "Sample: $SAMPLE"

# Define paths
BIGREC_DIR="BIGRec"
DLLM2REC_DIR="DLLM2Rec"
TOCF_DIR="$DLLM2REC_DIR/tocf/$DATASET"

# Ensure destination directory exists
mkdir -p "$TOCF_DIR"

# Construct source directory path
# Replace / with _ in model name for directory safety
SAFE_MODEL_NAME=$(echo "$BASE_MODEL" | tr '/' '_')
SRC_DIR="$BIGREC_DIR/results/$DATASET/$SAFE_MODEL_NAME/${SEED}_${SAMPLE}"

echo "Source Directory: $SRC_DIR"

# Copy files
# 1. Item Embeddings
# The embedding file is now in BIGRec/data/$DATASET/model_embeddings/$SAFE_MODEL_NAME.pt
EMBEDDING_SRC="$BIGREC_DIR/data/$DATASET/model_embeddings/${SAFE_MODEL_NAME}.pt"
if [ -f "$EMBEDDING_SRC" ]; then
    cp "$EMBEDDING_SRC" "$TOCF_DIR/all_embeddings.pt"
    echo "Copied all_embeddings.pt"
else
    echo "Warning: Item embedding file not found at $EMBEDDING_SRC"
    echo "Please run inference first to generate it."
fi

# 2. Rank and Confidence
# These are generated by evaluate.py in the result directory.
# The filenames are based on the input json filename.
# If we ran on train.json, it would be train_rank.txt and train_score.txt.
# If we ran on test_5000.json, it would be test_5000_rank.txt etc.
# We should look for *_rank.txt and *_score.txt in the result dir.

# Assuming we want to transfer the training data results (as per DLLM2Rec requirements "myrank_train.txt")
# We look for "train_rank.txt" specifically, or just copy whatever is there if it looks like rank data.
# But to be safe, let's assume the user ran inference on "train.json".

if [ -f "$SRC_DIR/train_rank.txt" ]; then
    cp "$SRC_DIR/train_rank.txt" "$TOCF_DIR/myrank_train.txt"
    echo "Copied myrank_train.txt"
elif [ -f "$SRC_DIR/test_5000_rank.txt" ]; then
     # Fallback or maybe user wants test rank? But DLLM2Rec asks for "myrank_train.txt".
     # I will warn if train_rank is missing.
     echo "Warning: train_rank.txt not found in $SRC_DIR"
     echo "Did you run inference on 'train.json'? (e.g. ./cmd/run_bigrec_inference.sh ... train.json)"
else
    echo "Warning: No rank file found in $SRC_DIR"
fi

if [ -f "$SRC_DIR/train_score.txt" ]; then
    cp "$SRC_DIR/train_score.txt" "$TOCF_DIR/confidence_train.txt"
    echo "Copied confidence_train.txt"
else
    echo "Warning: train_score.txt not found in $SRC_DIR"
fi

echo "Data transfer completed."
